### PR TITLE
fix memory corruption

### PR DESCRIPTION
**Pull request by vtjnash**
The cWigner3j explicitly first broadcasts a store of zero to w3j[1:j2+j3+1], so this memory must be valid or it corrupts the program state.

https://github.com/SHTOOLS/SHTOOLS/blob/93e77dcc6b36b2363f07d79d07ec47d86e6cba65/src/cWrapper.f95#L1972
```f95
        real(kind=c_double), dimension(j2+j3+1),intent(out) :: w3j
```
https://github.com/SHTOOLS/SHTOOLS/blob/93e77dcc6b36b2363f07d79d07ec47d86e6cba65/src/Wigner3j.f95#L117
```f95
    w3j = 0.0_dp
```

### CODE REVIEW

**Comment by eschnett** [comment]
@vtjnash You could, at your option, add the explanation above to the source code as a comment.

**Comment by eschnett** [comment]
There is a test failure. Do you think this is caused by floating-point accuracy?

**Comment by vtjnash** [comment]
It seems unclear, since that always uses the same random number seed. But also not related to this PR's code.

**Comment by eschnett** [comment]
Can you merge the `main` branch? I updated the CI setup.

**Comment by vtjnash** [comment]
No, you would need to enable that option in the repository settings first

**Comment by eschnett** [comment]
Ah, I thought that was a choice you made with your PR. I enabled the setting and merged the main branch.

**Comment by eschnett** [comment]
The problem is that `SHExpandLSQ` is returning `1e154` for some values. I can't reproduce it locally, but the `main` branch has the same problem.

**Pull request merged**
